from .error import (
    # Base
    AuthError,
    # Category 1: 400 Bad Request
    BadRequestError,
    InvalidFieldError,
    MissingRequiredFieldError,
    InvalidIdentifierError,
    WeakPasswordError,
    OTPValidationError,
    # Category 2: 401 Unauthorized
    AuthenticationError,
    InvalidCredentialsError,
    InvalidTokenError,
    TokenMissingError,
    TokenExpiredError,
    TokenMalformedError,
    TokenSignatureError,
    TokenRevokedError,
    SessionExpiredError,
    OTPInvalidError,
    OTPExpiredError,
    OAuthAuthenticationError,
    # Category 3: 403 Forbidden
    AuthorizationError,
    PermissionDeniedError,
    RoleMismatchError,
    RoleBlockedError,
    AccountStatusError,
    AccountSuspendedError,
    AccountInactiveError,
    # Category 4: 404 Not Found
    NotFoundError,
    UserNotFoundError,
    SessionNotFoundError,
    OTPNotFoundError,
    OAuthLinkNotFoundError,
    # Category 5: 409 Conflict
    ConflictError,
    AlreadyExistsError,
    EmailAlreadyExistsError,
    HandleAlreadyExistsError,
    PhoneAlreadyExistsError,
    OAuthAlreadyLinkedError,
    # Category 6: 500 Server & Config
    ServerError,
    DatabaseError,
    DatabaseIntegrityError,
    DatabaseConnectionError,
    ConfigurationError,
    InvalidConfigError,
    CookieNotConfiguredError,
    ServiceUnavailableError,
    # Category 7: External Services (Email, OAuth)
    ExternalServiceError,
    EmailError,
    EmailNotConfiguredError,
    EmailSendError,
    InvalidEmailPurposeError,
    OAuthError,
    OAuthNotConfiguredError,
    UnsupportedOAuthProviderError,
    OAuthCallbackError,
    OAuthUnlinkLockoutError,
    OAuthProviderError,
    # Category 8: Logging Subsystem
    LoggingError,
    LoggingDisabledError,
    LoggingNotConfiguredError,
    LogSourceInvalidError,
    LogUnsafeNameError,
    LogSnapshotNotFoundError,
    LogSnapshotAlreadyExistsError,
    LogCannotDeletePrimaryError,
)
from .handler import auth_exception_handler

__all__ = [
    # Base
    "AuthError",
    # Category 1: 400 Bad Request
    "BadRequestError",
    "InvalidFieldError",
    "MissingRequiredFieldError",
    "InvalidIdentifierError",
    "WeakPasswordError",
    "OTPValidationError",
    # Category 2: 401 Unauthorized
    "AuthenticationError",
    "InvalidCredentialsError",
    "InvalidTokenError",
    "TokenMissingError",
    "TokenExpiredError",
    "TokenMalformedError",
    "TokenSignatureError",
    "TokenRevokedError",
    "SessionExpiredError",
    "OTPInvalidError",
    "OTPExpiredError",
    "OAuthAuthenticationError",
    # Category 3: 403 Forbidden
    "AuthorizationError",
    "PermissionDeniedError",
    "RoleMismatchError",
    "RoleBlockedError",
    "AccountStatusError",
    "AccountSuspendedError",
    "AccountInactiveError",
    # Category 4: 404 Not Found
    "NotFoundError",
    "UserNotFoundError",
    "SessionNotFoundError",
    "OTPNotFoundError",
    "OAuthLinkNotFoundError",
    # Category 5: 409 Conflict
    "ConflictError",
    "AlreadyExistsError",
    "EmailAlreadyExistsError",
    "HandleAlreadyExistsError",
    "PhoneAlreadyExistsError",
    "OAuthAlreadyLinkedError",
    # Category 6: 500 Server & Config
    "ServerError",
    "DatabaseError",
    "DatabaseIntegrityError",
    "DatabaseConnectionError",
    "ConfigurationError",
    "InvalidConfigError",
    "CookieNotConfiguredError",
    "ServiceUnavailableError",
    # Category 7: External Services (Email, OAuth)
    "ExternalServiceError",
    "EmailError",
    "EmailNotConfiguredError",
    "EmailSendError",
    "InvalidEmailPurposeError",
    "OAuthError",
    "OAuthNotConfiguredError",
    "UnsupportedOAuthProviderError",
    "OAuthCallbackError",
    "OAuthUnlinkLockoutError",
    "OAuthProviderError",
    # Category 8: Logging Subsystem
    "LoggingError",
    "LoggingDisabledError",
    "LoggingNotConfiguredError",
    "LogSourceInvalidError",
    "LogUnsafeNameError",
    "LogSnapshotNotFoundError",
    "LogSnapshotAlreadyExistsError",
    "LogCannotDeletePrimaryError",
    # Handler
    "auth_exception_handler",
]